language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

# Don't do CI for WIP branches
branches:
  except:
    - /^WIP-.*$/

sudo: false

setup:
  - git fetch --unshallow && git fetch --tags

script:
  - python setup.py install

